### PR TITLE
Document the CDN

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
@carhartl 
What you think about documenting the CDN in the "installation" section?

Pros:
* People might rely less on `src/js.cookie.js` file on master that may be unstable
* Encourages the use of CDN for general sites instead of downloading the unminified source
* It provides a documented way to download the minified version instead of having to upload on each release (there were several requests in the past to provide the minified version)

Cons:
* It's hard to maintain the link consistently on each tagged release. cdnjs picks a new version **after** a tag is pushed[1]. If we rely in that, the tag view will retain the link of the previous version instead of the new one.

*[1]: I didn't tested if this is working, it is just how cdnjs documents the ["autoupdate" feature](https://github.com/cdnjs/cdnjs/tree/31eee715a9ffa7a6e739da45b7083c0b0dcbc266#enabling-gitrecommended-or-npm-auto-update) they rely upon and how I [set up](https://github.com/cdnjs/cdnjs/blob/31eee715a9ffa7a6e739da45b7083c0b0dcbc266/ajax/libs/js-cookie/package.json#L16-L23) js-cookie on cdnjs.*

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
@carhartl?

**Comment by carhartl** [comment]
I think this is a good idea, but that a tag would contain an outdated link is why I in the end would not want to merge it.

**Comment by carhartl** [comment]
It should be possible to automate this somehow in order to pull in the current version, at build time...

**Comment by FagnerMartinsBrack** [comment]
@carhartl 

> It should be possible to automate this somehow in order to pull in the current version, at build time...

Any idea how to do it?

As it currently stands, the major problem is that the resource will be unavailable (`404`) when the tag is created. It is necessary to wait cdnjs to pick up the new version after the new tag is pushed. The problem is the same even if we find a way to generate the link dynamically.

Maybe we can create the tagged release first with the outdated link (that is working), then after the new version is ready on cdnjs, create a new commit and change the tag pointer to the new version.

It's too complicated, there has to be an easier way to do this. I wonder if it's worth just to provide a link to https://cdnjs.com/libraries/js-cookie in the README and be done with it :tired_face: 

What do you think?

**Comment by carhartl** [comment]
I was thinking (naively) we could use https://github.com/geddski/grunt-release to automate the entire release process and along with it tackle updating the cdnjs reference. Though I haven't fully understood how the update process works at all with cdnjs...

**Comment by FagnerMartinsBrack** [comment]
> Though I haven't fully understood how the update process works at all with cdnjs...

Basically it works like this:

1. [Send a PR to cdnjs containing a file called `package.json` with the project meta data](https://github.com/cdnjs/cdnjs/pull/4713).
2. [The `package.json` should have the `autoupdate` property, so the data inside the `autoupdate` will be used for cdnjs to autoupdate the new version whenever a new tag is pushed in the target repository (so I hope)](https://github.com/cdnjs/cdnjs/pull/4713/files#diff-0f4cc8ef43a762b1e8a204882d3fe372R16).
3. [To add a library for the first time, create a directory with each previous file versions in the format `ajax/libs/js-cookie/x.x.x/js.cookie.min.js`, where `x.x.x` is one of all the previous versions of the library](https://github.com/cdnjs/cdnjs/tree/6ea9043f37ec548071e625ae729859935e99dec1/ajax/libs/js-cookie).
3. [After a few hours, the page is created according to the `package.json` information using the versions submitted in the first PR](http://cdnjs.com/libraries/js-cookie).

And that's it.

I may take a look in `grunt-release`, but I have failed to use it in previous projects. Tools that promises to abstract the release process do not work for all cases, except for very specific ones (and the ones who work for all cases have so many configs that you're better writing your own).

**Comment by FagnerMartinsBrack** [comment]
I found `jquery.cookie` is also in [jsDelivr](https://github.com/jsdelivr/jsdelivr/tree/master/files/jquery.cookie) CDN.

Even though it is available in other CDNs, if we decide to land any CDN documentation in this repository, it has to be cdnjs, the reasons are:

1. jsDelivr doesn't seems to be more popular than cdnjs (1k stars against 2k stars)
2. We only got a request to add cdnjs (#38)

**Comment by FagnerMartinsBrack** [comment]
Closing this in favor of #57

**Pull request closed without merging**
