### PR TITLE
Add migration notice and optional jquery support

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
@carhartl, should we:

* Force the user to rename the API upon migration, or
* Add the jQuery dependency, but make it optional and then remove it in [2.0 branch](https://github.com/js-cookie/js-cookie/tree/2.0)?

### CODE REVIEW

**Comment by carhartl** [comment]
I think we should go for the second option.

**Comment by FagnerMartinsBrack** [comment]
Ok

**Comment by FagnerMartinsBrack** [comment]
Lucky we [didn't choose to return anything](https://github.com/carhartl/jquery-cookie/pull/330) for module loaders.

**Comment by FagnerMartinsBrack** [comment]
@carhartl 

I've readded jQuery dependency and made it optional. Also I created some tests for AMD and nodejs module loaders.

Tell me what you think.

**Pull request closed without merging**
