### PR TITLE
Add license info in order to release with webjars

### PR DESCRIPTION
**Pull request by axos88**
Add MIT license

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Is this for automated tools that audit the licenses in all packages? Just to document the use case.

In the mean time are you getting the license information from `package.json`? Or this is a blocker for your use case?

**Comment by axos88** [comment]
This is a blocker, webjars requires the license to be specified in bower.json 
As a fallback it - as they state - it trolls through the git repo, searching for familiar files (license, license.md, and alike), but not MIT-LICENSE.TXT.

http://www.webjars.org/bower

**Comment by axos88** [comment]
I am currently using this by copying the file contents into my project as a workaround, but this would fix would be a welcome change.

**Comment by FagnerMartinsBrack** [comment]
Got it, thanks.

X-Ref: https://github.com/webjars/webjars/issues/1225

**Comment by axos88** [comment]
Can you please also release this change with a patch version bump in bower?

**Comment by FagnerMartinsBrack** [comment]
> Can you please also release this change with a patch version bump in bower?

Of course, Bower picks the new version automatically, when I release in npm it will automatically be released in Bower too =)

I will probably release a minor version tomorrow, but no worries, you can be sure this will be in the next version :)

**Comment by axos88** [comment]
Thanks. Can you please leave a message here when you do?

**Comment by FagnerMartinsBrack** [comment]
It's there: https://github.com/js-cookie/js-cookie/tree/v2.0.4

**Comment by axos88** [comment]
Awesome, thanks, it's working.

**Pull request closed without merging**
