### PR TITLE
travis: add node 12

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by carhartl** [comment]
Adding 12 is fine, but I’d like to keep all older LTS versions.

**Comment by carhartl** [comment]
Thanks! I will merge it on the 31st of December, when Node 8 reached end of life, haha!

**Comment by nikolas** [comment]
Oh woops, i'll add back in node 8 too.

**Comment by carhartl** [comment]
Thanks for reminding us!

**Pull request closed without merging**
