### PR TITLE
RFC 6265 compliance

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
- [x] cookie-value
- [x] cookie-name
- [x] docs

### CODE REVIEW

**Comment by carhartl** [comment]
:tada:

**Comment by FagnerMartinsBrack** [comment]
:D

I still need to test if using `encodeURIComponent/decodeURIComponent` is necessary for UTF-8 chars or if the browser and the servers can handle it accordingly. If not then need to discuss whether this should be handled by js-cookie or by the user.

It says (emphasis mine):

```
NOTE: Despite its name, the cookie-string is actually a sequence of
   octets, not a sequence of characters.  To convert the cookie-string
   (or components thereof) into a sequence of characters (e.g., for
   presentation to the user), the >>>>USER AGENT<<<< might wish to try using the
   UTF-8 character encoding [RFC3629] to decode the octet sequence.
   This decoding might fail, however, because not every sequence of
   octets is valid UTF-8.
```

**Comment by carhartl** [comment]
I think said conversion itself is handled by the client internals and it will never make it into `document.cookie`. So we only need to make sure the characters that aren't allowed are decoded properly?

**Comment by FagnerMartinsBrack** [comment]
That's my theory, but still I believe it's worth setting up a custom server to test exactly each browser's behavior in this matter. The spec unfortunately says:

> ... might wish to try using the UTF-8 character encoding ...

"might" might not be enough T.T

We still need some time for ppl to be aware of js-cookie, I believe there is no rush for a 2.0 release unless somebody requests so on npm. I am thinking about throwing some betas after js-cookie awareness is higher to see if there's any issues in the wild.

**Comment by carhartl** [comment]
Agreed. Btw, I was thinking, why are we naming it 2.0? Since it will be rather detached from jquery-cookie, we could just as well version it as 1.0?

**Comment by FagnerMartinsBrack** [comment]
Wouldn't that confuse the tags system? https://github.com/js-cookie/js-cookie/releases

**Comment by carhartl** [comment]
Yes, right, at least it will confuse everyone (one can push any tag any time).

**Pull request merged**
