### PR TITLE
Optimize the `var` declarations.

### PR DESCRIPTION
**Pull request by cdp1337**
This should result in slightly better compression ratios, (and less complaining from YUI).

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Can you show the difference in the GZip compression ratio? We have a task that does it called `grunt compare-size`, see [the docs here](https://github.com/rwaldron/grunt-compare-size) and the [task config](https://github.com/js-cookie/js-cookie/blob/5afa5d967d8f6b5d2a498926ae3e98e9a1c4857d/Gruntfile.js#L88).

**Comment by cdp1337** [comment]
Honestly I'm not sure, and grunt isn't in the debian repo...

**Comment by FagnerMartinsBrack** [comment]
By the way, you commited `js.cookie.min.js`, that's not necessary since we don't keep minified files in the source repo (we have plans to create a [release process that fixes that and other issues](https://github.com/js-cookie/js-cookie/issues/57)).

**Comment by FagnerMartinsBrack** [comment]
I tested this:

```
$ rmdir build /s /q
$ git reset --hard 5afa5d96
$ grunt && grunt compare_size:save:previous_commit
$ git reset --hard a6b08495
$ rmdir build /s /q
$ grunt && grunt compare_size
```

Result:

image

It does have a change in the raw size (`-14`) , but the gzipped size gains an increase of +2 bytes minified.

**Pull request closed without merging**
