### PR TITLE
Rethink converters

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
Inspired by https://github.com/carhartl/jquery-cookie/issues/151#issuecomment-25108455

### CODE REVIEW

**Comment by carhartl** [comment]
Great! Just wondering, what about the following alternative syntax:

```js
Cookies(function () { /* the converter function */ })
```

Maybe it's nonsense?

**Comment by FagnerMartinsBrack** [comment]
In this case how the reader of the code would know the function represents a converter? The user could use:

**Comment by FagnerMartinsBrack** [comment]
In this case how the reader of the code would know the function represents a converter?

Ok, it could be written as:

```javascript
Cookies(function converter() {
  /* ... */ 
});
```

But then in the `unescape` case things get cryptic.

```javascript
// What does unescape do here?
var cookies = Cookies(unescape);
```

**Comment by FagnerMartinsBrack** [comment]
Merging this in order to start new pull requests on top of branch 2.0 without code conflicts. Discussion can continue.

**Pull request merged**
