### PR TITLE
Attempt to fix Sauce Labs where the tunnel closes early.

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
This is the problem that is happening on CI (the tunnel closes early):

```shell
=> Starting Tunnel to Sauce Labs
=> Sauce Labs trying to open tunnel
>> => Sauce Labs Tunnel established
>> Connected to Saucelabs
 1 / 16 tests started
 2 / 16 tests started
 3 / 16 tests started
 4 / 16 tests started
=> Stopping Tunnel to Sauce Labs
 5 / 16 tests started
 6 / 16 tests started
>> 
>> Sauce Labs Tunnel disconnected
>> Error: POST https://saucelabs.com/rest/v1/js-cookie/js-tests failed.
>>     at /home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/src/utils.js:97:15
>>     at _rejected (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/node_modules/q/q.js:830:24)
>>     at /home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/node_modules/q/q.js:856:30
>>     at Promise.when (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/node_modules/q/q.js:1108:31)
>>     at Promise.promise.promiseDispatch (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/node_modules/q/q.js:774:41)
>>     at /home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/node_modules/q/q.js:590:44
>>     at runSingle (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/node_modules/q/q.js:123:13)
>>     at flush (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/node_modules/q/q.js:111:13)
>>     at process._tickCallback (node.js:458:13)
>>     Error: HTTP error (429)
>>         at /home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/src/utils.js:91:17
>>     From previous event:
>>         at Object.makeRequest (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/src/utils.js:86:8)
>>         at Job.start (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/src/Job.js:86:8)
>>         at getResult (/home/travis/build/js-cookie/js-cookie/node_modules/grunt-saucelabs/src/TestRunner.js:113:10)
Warning: Task "saucelabs-qunit:all" failed. Use --force to continue.
Aborted due to warnings.
The command "./travis.sh" exited with 3.
Done. Your build exited with 1.
```

**Attempt 1:**
<strike>I suspect this might be related to the Grunt upgrade, but wasn't spot early because Sauce only runs in commits or PRs created by [js-cookie members](https://github.com/orgs/js-cookie/people).</strike>

Even reverting Grunt it keeps failing.

[Inspecting the history](https://travis-ci.org/js-cookie/js-cookie/builds), it seems that it started failing between e9e61769c4e8 (pass) and dbce759 (fails):

screenshot 2016-04-16 19 53 02

[Here are the changes between both commits](https://github.com/js-cookie/js-cookie/compare/e9e6176...dbce759) above, nothing touches any Sauce Labs dependency. We use fixed `package.json` dependency versions, so it is likely to be an upstream issue.

Trying to restart [the build 522 on Travis](https://travis-ci.org/js-cookie/js-cookie/builds/123090165) that was previously passing, so that we can be 100% certain that this problem is not in js-cookie...

Confirmed! [Build 522 fails](https://travis-ci.org/js-cookie/js-cookie/builds/123090165) just by restarting it, it probably happens to all build. The problem is probably with Sauce Labs, creating bug report...

Report sent as a maximum priority level, case ID is 38251.

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
Bootstrap seems to be experiencing the same problem, [here is the latest build](https://travis-ci.org/twbs/bootstrap/jobs/123423096) failing on master for commit [795d2208](https://github.com/twbs/bootstrap/commit/795d2208b882e194e6059a1639e056e020d64072):

```shell
Running "saucelabs-qunit:all" (saucelabs-qunit) task
=> Starting Tunnel to Sauce Labs
>> Connected to Saucelabs
 1 / 13 tests started
 2 / 13 tests started
 3 / 13 tests started
 4 / 13 tests started
 5 / 13 tests started
 6 / 13 tests started
 7 / 13 tests started
 8 / 13 tests started
 9 / 13 tests started
 10 / 13 tests started
 11 / 13 tests started
 12 / 13 tests started
 13 / 13 tests started
=> Stopping Tunnel to Sauce Labs
>> 
>> Error: POST https://saucelabs.com/rest/v1/bootstrap/js-tests failed.
>>     at /home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/src/utils.js:97:15
>>     at _rejected (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/node_modules/q/q.js:830:24)
>>     at /home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/node_modules/q/q.js:856:30
>>     at Promise.when (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/node_modules/q/q.js:1108:31)
>>     at Promise.promise.promiseDispatch (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/node_modules/q/q.js:774:41)
>>     at /home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/node_modules/q/q.js:590:44
>>     at runSingle (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/node_modules/q/q.js:123:13)
>>     at flush (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/node_modules/q/q.js:111:13)
>>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>>     at process._tickCallback (internal/process/next_tick.js:98:9)
>>     Error: HTTP error (429)
>>         at /home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/src/utils.js:91:17
>>         at _combinedTickCallback (internal/process/next_tick.js:67:7)
>>         at process._tickCallback (internal/process/next_tick.js:98:9)
>>     From previous event:
>>         at Object.makeRequest (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/src/utils.js:86:8)
>>         at Job.start (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/src/Job.js:86:8)
>>         at getResult (/home/travis/build/twbs/bootstrap/node_modules/grunt-saucelabs/src/TestRunner.js:113:10)
Warning: Task "saucelabs-qunit:all" failed. Use --force to continue.
Aborted due to warnings.
Execution Time (2016-04-14 23:05:36 UTC)
babel:dev             1.6s  ▇▇▇ 6%
saucelabs-qunit:all  25.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 94%
Total 27.5s
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.
cache.2
store build cache
0.00s
10.45schanges detected, packing new archive
.
.
uploading archive
Done. Your build exited with 1.
```

@cvrebert?

**Comment by cvrebert** [comment]
Let me know how your Sauce bug report fares.
X-Ref: https://github.com/twbs/bootstrap/issues/18754

**Comment by FagnerMartinsBrack** [comment]
Response from Sauce Labs:

**Apr 16, 2016 03:04PM**

> Hi,

> We do seem to have an intermittent problem with email verification currently, which is being investigated. I have just manually verified your email address so you should be able to login again now. Please try and login and let me know if you continue to run into difficulties.

> With regards to your failing tests – this is JS Unit testing, correct? If so, are you seeing a 429 http response from the JS Unit REST api endpoint in your testing? If you are, you’re hitting some rate limiting, which seems to have been causing a problem for a few customers who are doing JS Unit testing over the last few days. We are also investigating this issue and I’m chasing up the current status.

> Regards,

**Apr 18, 2016 05:00AM**

> Hi,

> Regarding the rate limiting issue for js unit testing, a fix has been deployed and all is looking good. Please let me know if you continue to run into problems.

> Regards,

**Comment by FagnerMartinsBrack** [comment]
I have rerun the tests and all of them are passing for this PR now.

**Pull request closed without merging**
