### PR TITLE
Adding remove all

### PR DESCRIPTION
**Pull request by luanpotter**
This is an interesting feature that I tend to use in several places in most of my projects.  
I believe it would be a neat addition to the api.  
I'm open to suggestions, of course :)

### CODE REVIEW

**Comment by FagnerMartinsBrack** [comment]
We refrain from adding additional features to support unless there is enough evidence to justify the cost. Is there anything that should be done in `js-cookie` side that prevents you from extending `js-cookie` and doing something like this locally?

```javascript
Cookies.removeAll = function (attributes) {
 	Object.keys(Cookies.get()).forEach(function (cookie) {
 		Cookies.remove(cookie, attributes);
 	});
 };
```

`js-cookie` was created to remove the complexity of handling cookies and allow code like that to be created in the developer side. I see no reason for adding a new method that do not have the same benefit of abstracting `document.cookie = String`

This would be an amazing [one-line](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328)-like module though, and I would certainly use it to remove all cookies accessible in the current page.

@carhartl

**Comment by luanpotter** [comment]
No, it works with the extension -- in fact, I do that already in my projects.

I agree it would be overall clutter. And you gave a nice idea. I will see about making this one-line separate npm module, and so those who want can add this functionality with negligible effort, while not starting to attach little bits sparsely hanging around in the lib.

Thanks for the quick feedback!

**Comment by FagnerMartinsBrack** [comment]
When you create it, please link here for other ppl to find out. Maybe we can add something in the wiki linking to the module as a plugin? A self-answered question in StackOverflow would be amazing for SEO and visiblity too if the question constructs the url as `remove-all-cookies-using-javascript` ;)

**Comment by luanpotter** [comment]
Done: https://github.com/luanpotter/js-cookie-remove-all

**Comment by FagnerMartinsBrack** [comment]
:+1:

**Comment by FagnerMartinsBrack** [comment]
I have contributed with a PR for your repo, see https://github.com/luanpotter/js-cookie-remove-all/pull/1
Since we are delegating this to `js-cookie-remove-all`, I will assume the issue as solved.

**Pull request closed without merging**
