### PR TITLE
Separate the installation docs in sections

### PR DESCRIPTION
**Pull request by FagnerMartinsBrack**
Problem reported on #177
To view the updated README file, [click here](https://github.com/js-cookie/js-cookie/tree/readme-installation#readme).

### CODE REVIEW

**Comment by MartinMuzatko** [comment]
Please add the direct link to to the raw file: 
https://raw.githubusercontent.com/js-cookie/js-cookie/master/src/js.cookie.js

 > **Do not include the script directly from GitHub** (http://raw.github.com/...). The file is being served as text/plain and as such being blocked in Internet Explorer on Windows 7 for instance (because of the wrong MIME type). Bottom line: GitHub is not a CDN.


The problem with the paragraph above is, that users tend to ignore the text coming after "DO NOT" or just skip it, as it is not relevant. Putting the download file within a "do not" paragraph is not very intuitive, which is why I'd word it otherwise.

**Direct Download**

Download the file here: http://raw.github.com/...

**Do not include the script directly from GitHub** (http://raw.github.com/...). The file is being served as text/plain and as such being blocked in Internet Explorer on Windows 7 for instance (because of the wrong MIME type). Bottom line: GitHub is not a CDN.

**Comment by FagnerMartinsBrack** [comment]
@MartinMuzatko Thanks for the feedback! I have made some changes, can you take a look please?

**Comment by FagnerMartinsBrack** [comment]
But the way, looking at it again it doesn't seem worth pointing people out to the master branch, which is generally unstable. Ideally we should be pointing to the latest tagged release instead.

@MartinMuzatko what do you think?

**Comment by MartinMuzatko** [comment]
Good idea! Please update that.

**Comment by FagnerMartinsBrack** [comment]
> Good idea! Please update that.

Which one is a good idea, the relative url or a pointer always to the latest release?

**Comment by MartinMuzatko** [comment]
The latest tag. Thank you for asking again. I could be more precise.

**Pull request closed without merging**
